### ISSUE TITLE
3D object not being placed above aruco markers

### ISSUE THREAD

**Issue by tuhintiwari** [ajaymin28/Aruco_python#1]
Hi!
Thank you for this code. I am fairly new to OpenCV and OpenGL but my objective was to place the 3D object above the ArUco marker. For some reason, my 3D object goes to the background, while my video stream comes in the foreground. Is it what your code was supposed to achieve or am I missing something here?

**Comment by ajaymin28** [comment]
The code works properly. You might need to check your code again.

**Comment by BryceQing** [comment]
Hello! I can't load the video that contains in main, maybe the server is closed or the url is invalid?

**Comment by ajaymin28** [comment]
Check the url by opening normal opencv syntax. :)
