### ISSUE TITLE
Obj position problem

### ISSUE THREAD

**Issue by BryceQing** [ajaymin28/Aruco_python#2]
Hello, I have downloaded your code and changed webcam to the local camera and I also had calibrated my camera and load it's matrix and distcoff to yaml file. However, there shows a problem that the model position has offset to the center of the mark. I can't find out the problem.
![Capture](https://user-images.githubusercontent.com/41096251/67285632-81f05480-f50a-11e9-984d-586bae26bc13.png)

**Comment by vertok** [comment]
hey there. it‘s .obj problem, try to load the model in Blender. you could change modell position there

**Comment by ajaymin28** [comment]
@BryceQing as @vertok  explained its .obj problem. Let me know if changing .obj file fixed your problem or not.
